### PR TITLE
Add el_GR translation

### PR DESCRIPTION
**Pull request by e-me**

### CODE REVIEW

**Review by otacke — CHANGES_REQUESTED** [review]
Hi! And thanks once more. Could you please check your translation file against .en.json? The automated test reports a problem. https://github.com/otacke/h5p-game-map/actions/runs/7645210767/job/20832934541?pr=67

**Comment by e-me** [comment]
@otacke Seems like I was working on an older version of the file that was missing the Jan 22 change.   
I removed the `description for background music` so it should be ok now.

**Review by otacke — COMMENTED** [review]
The automated check still fails. I'll take a look later today.

**Review by otacke — COMMENTED** [review]
The structure seems to be off. Maybe you want to consider using https://translate-h5p.tk/ for translations ...

**Comment by e-me** [comment]
> The structure seems to be off. Maybe you want to consider using https://translate-h5p.tk/ for translations ...

I corrected the structure.

**Review by otacke — COMMENTED** [review]
The automated test still fails. You could do the same locally by using the H5P cli tool, that's what is used in the test.

I'll check your language file myself now, have a couple of spare minutes to spend.

**Comment by otacke** [comment]
@e-me You had replaced multiple `"default"` field labels with `"Προεπιλογή"` as well, not only field values. I really recommend to use https://translate-h5p.tk/ instead of doing all this by hand. Not only to rule out those syntax errors, but also to benefit from other features such as seeing how strings were translated in other content types, getting notifications when strings changed, etc.

**Comment by e-me** [comment]
> @e-me You had replaced multiple `"default"` field labels with `"Προεπιλογή"` as well, not only field values. I really recommend to use https://translate-h5p.tk/ instead of doing all this by hand. Not only to rule out those syntax errors, but also to benefit from other features such as seeing how strings were translated in other content types, getting notifications when strings changed, etc.

OK we will consider using weblate instead for new additions such as this one.  Thanks.

**Pull request merged**
