### PR TITLE
Language fr

### PR DESCRIPTION
**Pull request by ericacclermont**
Game map transcription in French

### CODE REVIEW

**Comment by ericacclermont** [comment]
Thank you in advance for the update for the French language

**Comment by otacke** [comment]
@ericacclermont I gladly will, but you closed the pull request. Anything wrong with it?

**Comment by ericacclermont** [comment]
I hope it's like this to reopen the pull request to add the French translation. Thanks again for your feedback.

**Comment by otacke** [comment]
@ericacclermont Thanks a lot! If you want translations of H5P content types to be more convenient, you can check out https://translate-h5p.tk

**Pull request merged**
